### ISSUE TITLE
Trying to run the AI player

### ISSUE THREAD

**Issue by k-godfrey22** [lancekindle/pysolation#2]
Howdy, I was going through your code. When I first launched the program, it is just a two-player game. I would like to use the AI player. How do I do this? I may have just missed it in the code. Thanks.

**Comment by k-godfrey22** [comment]
I found it in the code where you set the number of humand and bots. When I have the bot set to 1 and the human set to 1, the board does not respond

**Comment by lancekindle** [comment]
Have you tried the default case with 3 players, 1 bot?
I'm curious if you got this to work out of the box. (EDIT: I may have suboptimally changed this recently)
The human/robot counting isn't handled very well. Technically, human count dictates how many TOTAL players are in the board. Then from that total, robots are assigned. So 2 humans, 1 robot is actually 2 players, one of them being a robot (not 3 players)

**Comment by lancekindle** [comment]
to checkout my code before I started recently messing with it, try
git checkout e166dfe

**Comment by k-godfrey22** [comment]
hmm interesting. Even when i set the bot to 1 and the human to 2 the board still did not respond. I will try looking at that old commit

**Comment by lancekindle** [comment]
I force-updated the master tag to return to it's original place, and made a new branch for the experimental stuff I was doing.
Thanks for letting me know I had borken the master branch :)
Did you ever get the players working?
